[[main]]
name = "Posts"
url = "/posts"
weight = 10

[[main]]
name = "Github"
pre = "github"
url = "https://github.com/felstedrobotics"
weight = 30

[[footer]]
name = "Felsted Robotics"
identifier = "U2EYei5dWc"
weight = 9999
